### ISSUE TITLE
More than one

### ISSUE THREAD

**Issue by efestudio** [codrops/MagneticButtons#1]
Hi there and first of all congrats for your amazing job.
I've been playing around with these magnetic buttons and I am wondering if is it possible to add more than only one on the same HTML, I've been trying it with no luck. could you point us to the right direction to achieve that?

Thanks heaps

**Comment by botelho** [comment]
Hi,
so for the first demo, just repeat the button in index.html and in demo1/index.js do:
 
`[...document.querySelectorAll('.button')].forEach(buttonEl => {
      const button = new ButtonCtrl(buttonEl);
      button.on('enter', () => cursor.enter());
      button.on('leave', () => cursor.leave());
});`

**Comment by xyralothep** [comment]
Hi, I've tried using this code to add multiple buttons to the page.  Sometimes the page loads fine, sometimes not all the button hover effects load, and sometimes none of them load.

http://odyssey.weareflourishstaging.com/

I've also changed the styling of the buttons a bit but not sure this would effect the JavaScript running.  Any ideas?  Thanks
