### ISSUE TITLE
Wrong effect position

### ISSUE THREAD

**Issue by mlanfranchi** [codrops/MagneticButtons#4]
Hello, i was testing the index"1" when i face this issue:
i put about 70 span between the header closure and button start(to make the page higher than the screen) and others 30 below the button closure.
The problem is that now the magnetic effect no longer starts from the position of the button but a little higher even if I reload the page.

**Comment by mlanfranchi** [comment]
If someone needed i found the solution:

1) Inside buttonCtrl.js add

`this.adjustedRect = adjustBoundingRect(this.rect.bottom, this.rect.left, this.rect.right, this.rect.top, this.rect.height, this.rect.width, this.rect.x, this.rect.y, window.scrollX, window.scrollY);`

below `this.rect = this.DOM.el.getBoundingClientRect();`

2) replace each `this.rect` except the getter one with `this.adjustedRect`

3) at last go to utils.js and add

`const adjustBoundingRect = (bottom, left, right, top, height, width, x, y, scrollX, scrollY) => {
    const adjustedRect = {
        bottom: bottom,
        top: top + scrollY,
        left: left + scrollX,
        right: right,
        height: height,
        width: width,
        x: x,
        y: y
    };
    return adjustedRect
}`

(remember to export and import the adjustBoundingRect function)

**Comment by mlanfra** [comment]
:bowtie:
